id: I0D275747
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.101026
last_modified: 2023-02-09 14:46:46.101136
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: zh
bases:
  D044:
    base_file: D044.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
